<a href="https://colab.research.google.com/github/FelipeFlorezO/Analytics/blob/main/tiposdedatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tipos de datos en estadística inferencial 

Aquí tenemos en cuenta los diferentes tipos de datos o variables estructuradas en cualquier problema de ciencia de datos.

* datos categóricos: ordinales y nominales
* datos numéricos: discretos y continuos

a continuación exploraremos un dataset que contiene todos estos tipos de datos: https://www.kaggle.com/lepchenkov/usedcarscatalog

In [2]:
import pandas as pd
import numpy as np

In [6]:
from google.colab import drive

In [7]:
drive.mount('/content/drive')

Mounted at /content/drive

In [14]:
import csv

In [15]:
df = pd.read_csv('cars.csv', header = None, delimiter="\t", quoting=csv.QUOTE_NONE, encoding='utf-8')

In [28]:
df

                                                       0
0      manufacturer_name,model_name,transmission,colo...
1      Subaru,Outback,automatic,silver,190000,2010,ga...
2      Subaru,Outback,automatic,blue,290000,2002,gaso...
3      Subaru,Forester,automatic,red,402000,2001,gaso...
4      Subaru,Impreza,mechanical,blue,10000,1999,gaso...
...                                                  ...
55782  Chrysler,300,automatic,silver,290000,2000,gaso...
55783  Chrysler,PT Cruiser,mechanical,blue,321000,200...
55784  Chrysler,300,automatic,blue,777957,2000,gasoli...
55785  Chrysler,PT Cruiser,mechanical,black,20000,200...
55786  Chrysler,Voyager,automatic,silver,297729,2000,...

[55787 rows x 1 columns]

Warning: total number of rows (55787) exceeds max_rows (20000). Limiting to first (20000) rows.

los tipos de datos de cada columna en el dataset se pueden obtener directamente con `pandas.DataFrame.dtypes`

In [29]:
df.dtypes

0    object
dtype: object

Ahora, con la libreria pandas podemos generar un conjunto completo de estadisticos descriptivos del dataset usando `pandas.DataFrame.describe()`

In [31]:
df.describe()

                                                        0
count                                               55787
unique                                              38495
top     Skoda,Rapid,mechanical,brown,0,2019,gasoline,F...
freq                                                   10